name: Build and Run Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
    - run: sudo apt-get update && sudo apt-get install -y docker.io      
        
    - name: Build Docker image
      run: docker build -t generate-sitemap .

    - name: Run Docker container
      run: docker run generate-sitemap
